# EDAs investigation on DVSGesture
python train.py --encoder1="3dcnn" --encoder2="3dcnn" --dataset="dvsgesture" --edas="background_activity"
python train.py --encoder1="3dcnn" --encoder2="3dcnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity"
python train.py --encoder1="3dcnn" --encoder2="3dcnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop"
python train.py --encoder1="3dcnn" --encoder2="3dcnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop"
python train.py --encoder1="3dcnn" --encoder2="3dcnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,static_translation,static_rotation"
python train.py --encoder1="3dcnn" --encoder2="3dcnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,dynamic_translation,dynamic_rotation"
python train.py --encoder1="3dcnn" --encoder2="3dcnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn"
python train.py --encoder1="3dcnn" --encoder2="3dcnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn, cutout"
python train.py --encoder1="3dcnn" --encoder2="3dcnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn, event_drop"
python train.py --encoder1="3dcnn" --encoder2="3dcnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn, event_copy"
python train.py --encoder1="3dcnn" --encoder2="3dcnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn, event_copy_drop"

python train.py --encoder1="cnn" --encoder2="cnn" --dataset="dvsgesture" --edas="background_activity"
python train.py --encoder1="cnn" --encoder2="cnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity"
python train.py --encoder1="cnn" --encoder2="cnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop"
python train.py --encoder1="cnn" --encoder2="cnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop"
python train.py --encoder1="cnn" --encoder2="cnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,static_translation,static_rotation"
python train.py --encoder1="cnn" --encoder2="cnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,dynamic_translation,dynamic_rotation"
python train.py --encoder1="cnn" --encoder2="cnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn"
python train.py --encoder1="cnn" --encoder2="cnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn, cutout"
python train.py --encoder1="cnn" --encoder2="cnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn, event_drop"
python train.py --encoder1="cnn" --encoder2="cnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn, event_copy"
python train.py --encoder1="cnn" --encoder2="cnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn, event_copy_drop"

python train.py --encoder1="snn" --encoder2="snn" --dataset="dvsgesture" --edas="background_activity"
python train.py --encoder1="snn" --encoder2="snn" --dataset="dvsgesture" --edas="background_activity,flip_polarity"
python train.py --encoder1="snn" --encoder2="snn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop"
python train.py --encoder1="snn" --encoder2="snn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop"
python train.py --encoder1="snn" --encoder2="snn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,static_translation,static_rotation"
python train.py --encoder1="snn" --encoder2="snn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,dynamic_translation,dynamic_rotation"
python train.py --encoder1="snn" --encoder2="snn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn"
python train.py --encoder1="snn" --encoder2="snn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn, cutout"
python train.py --encoder1="snn" --encoder2="snn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn, event_drop"
python train.py --encoder1="snn" --encoder2="snn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn, event_copy"
python train.py --encoder1="snn" --encoder2="snn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn, event_copy_drop"

python train.py --encoder1="snn" --encoder2="3dcnn" --dataset="dvsgesture" --edas="background_activity"
python train.py --encoder1="snn" --encoder2="3dcnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity"
python train.py --encoder1="snn" --encoder2="3dcnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop"
python train.py --encoder1="snn" --encoder2="3dcnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop"
python train.py --encoder1="snn" --encoder2="3dcnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,static_translation,static_rotation"
python train.py --encoder1="snn" --encoder2="3dcnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,dynamic_translation,dynamic_rotation"
python train.py --encoder1="snn" --encoder2="3dcnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn"
python train.py --encoder1="snn" --encoder2="3dcnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn, cutout"
python train.py --encoder1="snn" --encoder2="3dcnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn, event_drop"
python train.py --encoder1="snn" --encoder2="3dcnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn, event_copy"
python train.py --encoder1="snn" --encoder2="3dcnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn, event_copy_drop"

python train.py --encoder1="snn" --encoder2="cnn" --dataset="dvsgesture" --edas="background_activity"
python train.py --encoder1="snn" --encoder2="cnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity"
python train.py --encoder1="snn" --encoder2="cnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop"
python train.py --encoder1="snn" --encoder2="cnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop"
python train.py --encoder1="snn" --encoder2="cnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,static_translation,static_rotation"
python train.py --encoder1="snn" --encoder2="cnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,dynamic_translation,dynamic_rotation"
python train.py --encoder1="snn" --encoder2="cnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn"
python train.py --encoder1="snn" --encoder2="cnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn, cutout"
python train.py --encoder1="snn" --encoder2="cnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn, event_drop"
python train.py --encoder1="snn" --encoder2="cnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn, event_copy"
python train.py --encoder1="snn" --encoder2="cnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn, event_copy_drop"

# Linear Evaluation protocols for all  datasets
python train.py --encoder1="snn" --encoder2="snn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn, event_copy_drop"
python train.py --encoder1="cnn" --encoder2="cnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn, event_copy_drop"
python train.py --encoder1="3dcnn" --encoder2="3dcnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn, event_copy_drop"
python train.py --encoder1="snn" --encoder2="cnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn, event_copy_drop"
python train.py --encoder1="snn" --encoder2="3dcnn" --dataset="dvsgesture" --edas="background_activity,flip_polarity,crop,geostatdyn, event_copy_drop"

python train.py --encoder1="snn" --encoder2="snn" --dataset="asl-dvs" --edas="background_activity,flip_polarity,crop,geostatdyn, event_copy_drop"
python train.py --encoder1="cnn" --encoder2="cnn" --dataset="asl-dvs" --edas="background_activity,flip_polarity,crop,geostatdyn, event_copy_drop"
python train.py --encoder1="3dcnn" --encoder2="3dcnn" --dataset="asl-dvs" --edas="background_activity,flip_polarity,crop,geostatdyn, event_copy_drop"
python train.py --encoder1="snn" --encoder2="cnn" --dataset="asl-dvs" --edas="background_activity,flip_polarity,crop,geostatdyn, event_copy_drop"
python train.py --encoder1="snn" --encoder2="3dcnn" --dataset="asl-dvs" --edas="background_activity,flip_polarity,crop,geostatdyn, event_copy_drop"

python train.py --encoder1="snn" --encoder2="snn" --dataset="n-caltech101" --edas="background_activity,flip_polarity,crop,geostatdyn, event_copy_drop"
python train.py --encoder1="cnn" --encoder2="cnn" --dataset="n-caltech101" --edas="background_activity,flip_polarity,crop,geostatdyn, event_copy_drop"
python train.py --encoder1="3dcnn" --encoder2="3dcnn" --dataset="n-caltech101" --edas="background_activity,flip_polarity,crop,geostatdyn, event_copy_drop"
python train.py --encoder1="snn" --encoder2="cnn" --dataset="n-caltech101" --edas="background_activity,flip_polarity,crop,geostatdyn, event_copy_drop"
python train.py --encoder1="snn" --encoder2="3dcnn" --dataset="n-caltech101" --edas="background_activity,flip_polarity,crop,geostatdyn, event_copy_drop"

